#!/bin/dash

# Useful scripts
wifi(){
test "`nmcli --terse --fields STATE general status`" = "disconnected" && echo -n "----" || \
nmcli --terse --fields IN-USE,SSID dev wifi | grep "*" | awk '{split($0,a,":") ; print a[2]}'
}
workspace() {
	xdotool get_desktop
}
battery() {
	BATC=/sys/class/power_supply/BAT1/capacity
	BATS=/sys/class/power_supply/BAT1/status
	test "`cat $BATS`" = "Charging" && echo -n '+' || echo -n '-'
	sed -n p $BATC
}
clock() {
	#HOUR=$(date '+%T') # HH:MM:SS
	HOUR=$(date '+%H:%M')
	echo $HOUR
}
memused() {
	free -mhw | grep -E Mem: | awk '{print $3,"/",$2}'
}

FG='#aaaaaa'
BG='#1a1a1a'

conky -c barconky | dzen2 -e - -h '16'  -ta r -fg $FG -bg $BG -fn 'LiberationMono-Regular'
