#!/bin/dash

FG='#aaaaaa'
BG='#1a1a1a'
RESW=$xrandr | grep '*' | awk '{gsub (" ", "", $0) ; split($0,a,"x") ; print a[1]}'
W=300
X=$(($RESW-$W))

conks | dzen2 -p -x $X -y "20" -w $W -l "5"  -ta 'c'  \
	-title-name 'sysinfo' -e 'onstart=uncollapse;button1=exit;button3=exit' -fg $FG -bg $BG -fn 'LiberationMono-Regular'
