#!/bin/dash

test "`nmcli --terse --fields STATE general status`" = "disconnected" && echo -n "----" || \
nmcli --terse --fields IN-USE,SSID dev wifi | grep "*" | awk '{split($0,a,":") ; print a[2]}'
